SOURCES := rgb.cpp rgb/task.cpp rgb/blinker_task.cpp rgb/color.cpp rgb/fader_task.cpp rgb/light.cpp rgb/watchdog.cpp rgb/led_breather_task.cpp rgb/led_strober_task.cpp rgb/input.cpp
# SOURCES := echo.cpp

# BOARD := nano328
BOARD := pro328

include arduino.mk
