SOURCES := aphex.cpp aphex/task.cpp aphex/blinker_task.cpp aphex/color.cpp aphex/fader_task.cpp aphex/light.cpp aphex/watchdog.cpp aphex/led_breather_task.cpp aphex/led_strober_task.cpp aphex/input.cpp
# SOURCES := echo.cpp

# BOARD := nano328
BOARD := pro328

include arduino.mk
